<a href="https://colab.research.google.com/github/Adrianus-Bagas/CAD_Coding_Test/blob/main/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extract Dataset

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_csv('/content/drive/MyDrive/dataset/movies.csv')
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

# Transform Dataset

In [4]:
df = df.dropna(subset=["STARS"])
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [5]:
import re
def findDirector(x):
  result = re.search('Director:\n(.*)\n| \n Star', x)
  if result==None:
    return "Anonymous Director"
  else:
    return result.group(1)
def findStars(x):
  result = re.search('Stars:\n(.*), \n(.*), \n(.*), \n(.*)\n', x)
  if result==None:
    return "Anonymous Stars"
  else:
    return ', '.join(list(result.groups()))

In [6]:
df["Director"] = df["STARS"].apply(findDirector)
df["Stars"] = df["STARS"].apply(findStars)

In [7]:
df = df.drop(['ONE-LINE','STARS','VOTES','RunTime'],axis=1)
df

,MOVIES,YEAR,GENRE,RATING,Gross,Director,Stars
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,NaN,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc..."
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,NaN,Anonymous Director,"Chris Wood, Sarah Michelle Gellar, Lena Headey..."
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,NaN,Anonymous Director,"Andrew Lincoln, Norman Reedus, Melissa McBride..."
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,NaN,Anonymous Director,"Justin Roiland, Chris Parnell, Spencer Grammer..."
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,NaN,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby..."
...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,NaN,Anonymous Director,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo..."
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,NaN,Anonymous Director,Anonymous Stars
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,NaN,Orlando von Einsiedel,Anonymous Stars
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,NaN,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J..."
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,NaN,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,..."

In [8]:
def findGenre(x):
  result = re.search('\n(.*)', x)
  if result==None:
    return "Anonymous Genre"
  else:
    return result.group(1)

In [9]:
df["GENRE"] = df["GENRE"].apply(str)
df["GENRE"] = df["GENRE"].apply(findGenre)

In [10]:
df

,MOVIES,YEAR,GENRE,RATING,Gross,Director,Stars
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,NaN,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc..."
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,NaN,Anonymous Director,"Chris Wood, Sarah Michelle Gellar, Lena Headey..."
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,NaN,Anonymous Director,"Andrew Lincoln, Norman Reedus, Melissa McBride..."
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,NaN,Anonymous Director,"Justin Roiland, Chris Parnell, Spencer Grammer..."
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,NaN,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby..."
...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,NaN,Anonymous Director,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo..."
9995,Arcane,(2021– ),"Animation, Action, Adventure",NaN,NaN,Anonymous Director,Anonymous Stars
9996,Heart of Invictus,(2022– ),"Documentary, Sport",NaN,NaN,Orlando von Einsiedel,Anonymous Stars
9997,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,NaN,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J..."
9998,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,NaN,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,..."

In [11]:
p = df["Director"].unique()

In [12]:
ip = []
for i in range(len(p)):
  id = 'Dir('+str(i+1)+')'
  ip.append(id)

In [13]:
m = df["MOVIES"].unique()
im = []
for i in range(len(m)):
  id = 'M('+str(i+1)+')'
  im.append(id)

In [14]:
id_film = {m[i]: im[i] for i in range(len(m))}

In [15]:
def movieid(x):
  return id_film[x]

In [16]:
df["ID Movie"] = df["MOVIES"].apply(movieid)

In [17]:
id_director = {p[i]:ip[i] for i in range(len(p))}

In [18]:
def directorid(x):
  return id_director[x]

In [19]:
df["ID Director"] = df["Director"].apply(directorid)

In [20]:
df

,MOVIES,YEAR,GENRE,RATING,Gross,Director,Stars,ID Movie,ID Director
0,Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,NaN,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc...",M(1),Dir(1)
1,Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,NaN,Anonymous Director,"Chris Wood, Sarah Michelle Gellar, Lena Headey...",M(2),Dir(2)
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,NaN,Anonymous Director,"Andrew Lincoln, Norman Reedus, Melissa McBride...",M(3),Dir(2)
3,Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,NaN,Anonymous Director,"Justin Roiland, Chris Parnell, Spencer Grammer...",M(4),Dir(2)
4,Army of Thieves,(2021),"Action, Crime, Horror",NaN,NaN,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby...",M(5),Dir(3)
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,NaN,Anonymous Director,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo...",M(6813),Dir(2)
9995,Arcane,(2021– ),"Animation, Action, Adventure",NaN,NaN,Anonymous Director,Anonymous Stars,M(6816),Dir(2)
9996,Heart of Invictus,(2022– ),"Documentary, Sport",NaN,NaN,Orlando von Einsiedel,Anonymous Stars,M(6817),Dir(1146)
9997,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,NaN,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J...",M(6813),Dir(3141)
9998,The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,NaN,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,...",M(6813),Dir(3141)

# Load Clean Data

In [21]:
director_table = pd.DataFrame({'ID_Director' : ip,'Director_Name':p})

In [22]:
director_table

     ID_Director          Director_Name
0         Dir(1)        Peter Thorwarth
1         Dir(2)     Anonymous Director
2         Dir(3)  Matthias Schweighöfer
3         Dir(4)     Augustine Frizzell
4         Dir(5)        Navot Papushado
...          ...                    ...
3136   Dir(3137)            Lang Fisher
3137   Dir(3138)        Paul Wilmshurst
3138   Dir(3139)      Anthony Philipson
3139   Dir(3140)          Nicolai Rohde
3140   Dir(3141)       Jovanka Vuckovic

[3141 rows x 2 columns]

In [23]:
df = df.drop(['Director'],axis=1)

In [24]:
movie_table = df[['ID Movie','MOVIES','YEAR','GENRE','RATING','Stars','Gross','ID Director']]
movie_table.columns = ['ID_Movie','Movie_Name','Year','Genre','Rating','Stars','Gross','ID_Director']

In [25]:
movie_table

,ID_Movie,Movie_Name,Year,Genre,Rating,Stars,Gross,ID_Director
0,M(1),Blood Red Sky,(2021),"Action, Horror, Thriller",6.1,"Peri Baumeister, Carl Anton Koch, Alexander Sc...",NaN,Dir(1)
1,M(2),Masters of the Universe: Revelation,(2021– ),"Animation, Action, Adventure",5.0,"Chris Wood, Sarah Michelle Gellar, Lena Headey...",NaN,Dir(2)
2,M(3),The Walking Dead,(2010–2022),"Drama, Horror, Thriller",8.2,"Andrew Lincoln, Norman Reedus, Melissa McBride...",NaN,Dir(2)
3,M(4),Rick and Morty,(2013– ),"Animation, Adventure, Comedy",9.2,"Justin Roiland, Chris Parnell, Spencer Grammer...",NaN,Dir(2)
4,M(5),Army of Thieves,(2021),"Action, Crime, Horror",NaN,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby...",NaN,Dir(3)
...,...,...,...,...,...,...,...,...
9994,M(6813),The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo...",NaN,Dir(2)
9995,M(6816),Arcane,(2021– ),"Animation, Action, Adventure",NaN,Anonymous Stars,NaN,Dir(2)
9996,M(6817),Heart of Invictus,(2022– ),"Documentary, Sport",NaN,Anonymous Stars,NaN,Dir(1146)
9997,M(6813),The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J...",NaN,Dir(3141)
9998,M(6813),The Imperfects,(2021– ),"Adventure, Drama, Fantasy",NaN,"Morgan Taylor Campbell, Jennifer Cheon Garcia,...",NaN,Dir(3141)

In [26]:
director_table.to_csv('/content/drive/MyDrive/dataset/director_table.csv')
movie_table.to_csv('/content/drive/MyDrive/dataset/movie_table.csv')